Running cluster for deep fits
124224 124225 normal
Running object 124224
Min gap is: 10.972656
Min gap is: 0.00390625
New time_gap is :0.00790625
Min gap is: 0.00390625
New time_gap is :0.00790625
Min gap is: 0.00390625
New time_gap is :0.00790625
Counts: {'r': 21, 'i': 54, 'z': 18}
Mu: {'g': 0.100636944, 'r': 0.114395075, 'i': 0.18499056, 'z': 0.30648738}
No handles with labels found to put in legend.
/usr/local/python/3.7.0/lib/python3.7/site-packages/scipy/optimize/minpack.py:794: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)
Variable??
0
0
Non-Variable source in g
Variable??
0.021267388935384962
3.194141612053106
Variable Source in r!!
Variable??
0.030363024737409587
1.5774889197018085
Non-Variable source in i
Variable??
0.06689747993179528
2.6061443366640975
Non-Variable source in z
Variable:    1/4
Var Bands:   r
Slope:       [1, 1, 1, 1]
Slope Error: [0.0, 0, 0.2198986848518492, inf]
intercepts:  [0, 0, 0.1417777070424002, -75.66418855959766]
Int Error:   [0.0, 0, 0.0882767219350611, inf]
StDev:       [0.0, 0.067181975, 0.050878633, 0.17204937]
Spread:      0/4
Spread values: 
ClusterEmcee2_linear_mu_all_and_single_fast.py:865: RuntimeWarning: invalid value encountered in multiply
  err_mod += np.sqrt(err**2 + dMu_dict_err[color]**2 + (flux-dMu_dict[color])**2/scale_dict[color]**2 * scale_err[color]**2)/scale_dict[color]*color_sort_ones[color_dict[color]]
Traceback (most recent call last):
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 868, in <module>
    perform_emcee_step2(time, flux_mod, err_mod**2, dMu_dict, scale_dict, color_sort_ones, ROW, mu, var_count)
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 609, in perform_emcee_step2
    sampler.run_mcmc(pos, 200)
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 384, in run_mcmc
    for results in self.sample(initial_state, iterations=nsteps, **kwargs):
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 285, in sample
    state.log_prob, state.blobs = self.compute_log_prob(state.coords)
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 456, in compute_log_prob
    raise ValueError("Probability function returned NaN")
ValueError: Probability function returned NaN
srun: error: ccc0241: task 0: Exited with exit code 1
