Running cluster for deep fits
37884 37885 normal
Running object 37884
Not enough g observations!
Min gap is: 0.00390625
New time_gap is :0.00790625
Number of observations now:  5
Min gap is: 0.00390625
New time_gap is :0.00790625
Number of observations now:  59
Min gap is: 0.00390625
New time_gap is :0.00790625
Number of observations now:  94
Counts: {'r': 5, 'i': 57, 'z': 90}
Mu: {'g': 0.0, 'r': 0.13472593, 'i': 0.24718547, 'z': 0.42520237}
No handles with labels found to put in legend.
/usr/local/python/3.7.0/lib/python3.7/site-packages/scipy/optimize/minpack.py:794: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)
Variable??
0
0
Non-Variable source in g
Variable??
0.02795433832372874
8.418200430962852
Variable Source in r!!
Variable??
0.039995091033284025
1.6277662657402314
Non-Variable source in i
Variable??
0.06437975566910045
1.5871651524473536
Non-Variable source in z
Variable:    1/4
Var Bands:   r
Slope:       [1, 1, 1, 1]
Slope Error: [0.0, 0, 0.3679932317789676, inf]
intercepts:  [0, 0, 0.14483038331952905, 1.205031366093451]
Int Error:   [0.0, 0, 0.18366726693571075, inf]
StDev:       [0.0, 0.36422113, 0.06347849, 0.09186902]
Spread:      0/4
Spread values: 
ClusterEmcee2_linear_mu_all_and_single_fast.py:870: RuntimeWarning: invalid value encountered in multiply
  err_mod += np.sqrt(err**2 + dMu_dict_err[color]**2 + (flux-dMu_dict[color])**2/scale_dict[color]**2 * scale_err[color]**2)/scale_dict[color]*color_sort_ones[color_dict[color]]
ClusterEmcee2_linear_mu_all_and_single_fast.py:225: RuntimeWarning: invalid value encountered in double_scalars
  lp_app = lp + lnlike_fast_linear.lnlike(theta, x, y, yerr)
Traceback (most recent call last):
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 873, in <module>
    perform_emcee_step2(time, flux_mod, err_mod**2, dMu_dict, scale_dict, color_sort_ones, ROW, mu, var_count)
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 614, in perform_emcee_step2
    sampler.run_mcmc(pos, 200)
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 384, in run_mcmc
    for results in self.sample(initial_state, iterations=nsteps, **kwargs):
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 285, in sample
    state.log_prob, state.blobs = self.compute_log_prob(state.coords)
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 456, in compute_log_prob
    raise ValueError("Probability function returned NaN")
ValueError: Probability function returned NaN
srun: error: ccc0249: task 0: Exited with exit code 1
