Running cluster for deep fits
62436 62437 normal
Running object 62436
Not enough g observations!
Min gap is: 0.00390625
New time_gap is :0.00790625
Number of observations now:  14
Min gap is: 0.00390625
New time_gap is :0.00790625
Number of observations now:  64
Min gap is: 0.0078125
Number of observations now:  16
Counts: {'r': 14, 'i': 63, 'z': 16}
Mu: {'g': 0.0, 'r': 0.15197906, 'i': 0.24801494, 'z': 0.3457173}
No handles with labels found to put in legend.
/usr/local/python/3.7.0/lib/python3.7/site-packages/scipy/optimize/minpack.py:794: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)
Variable??
0
0
Non-Variable source in g
Variable??
0.024811801182426693
6.367703422192731
Variable Source in r!!
Variable??
0.034040515279694546
1.2129433574994481
Non-Variable source in i
Variable??
0.07152530550956726
0.5991703864778428
Non-Variable source in z
Variable:    1/4
Var Bands:   r
Slope:       [1, 1, 1, 1]
Slope Error: [0.0, 0, 0.8143307177087351, inf]
intercepts:  [0, 0, 0.33665723543424786, 72.38954685248022]
Int Error:   [0.0, 0, 0.24116430357043922, inf]
StDev:       [0.0, 0.07561203, 0.057529382, 0.082619585]
Spread:      0/4
Spread values: 
ClusterEmcee2_linear_mu_all_and_single_fast.py:870: RuntimeWarning: invalid value encountered in multiply
  err_mod += np.sqrt(err**2 + dMu_dict_err[color]**2 + (flux-dMu_dict[color])**2/scale_dict[color]**2 * scale_err[color]**2)/scale_dict[color]*color_sort_ones[color_dict[color]]
Traceback (most recent call last):
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 873, in <module>
    perform_emcee_step2(time, flux_mod, err_mod**2, dMu_dict, scale_dict, color_sort_ones, ROW, mu, var_count)
  File "ClusterEmcee2_linear_mu_all_and_single_fast.py", line 614, in perform_emcee_step2
    sampler.run_mcmc(pos, 200)
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 384, in run_mcmc
    for results in self.sample(initial_state, iterations=nsteps, **kwargs):
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 285, in sample
    state.log_prob, state.blobs = self.compute_log_prob(state.coords)
  File "/home/thrush2/caps_dir/mypython3/emcee/ensemble.py", line 456, in compute_log_prob
    raise ValueError("Probability function returned NaN")
ValueError: Probability function returned NaN
srun: error: ccc0249: task 0: Exited with exit code 1
