/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py:545: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "
ClusterEmcee2_linear_mu_2step.py:273: RuntimeWarning: divide by zero encountered in divide
  Fg1 = (Fg1 - mu_r)/mu_r
/home/thrush2/.local/lib/python2.7/site-packages/numpy/lib/polynomial.py:584: RuntimeWarning: invalid value encountered in true_divide
  lhs /= scale
('900', '1000', 'normal')
Running object 900
0.0
{'i': 21, 'z': 94}
{'i': 0.3992958, 'r': 0.0, 'z': 0.8791461, 'g': 0.0}
Variable??
0
Non-Variable source in g
Variable??
0
Non-Variable source in r
Variable??
0.7669875713645332
Non-Variable source in i
Variable??
0.03509124308948186
Non-Variable source in z
Slope:       [1, 1, 1, 1]
Slope Error: [0.0, 0, 0.0, 0.0]
intercepts:  [0, 0, 0, 0]
Int Error:   [0.0, 0, 0.0, 0.0]
StDev:       [0.0, 0.0, 0.05571678, 0.10548151]
('ROW:', 900, 'Tau:', '1.2487946920122497', 'V:', '-1.3142593807182925')
115
Traceback (most recent call last):
  File "ClusterEmcee2_linear_mu_2step.py", line 552, in <module>
    perform_emcee_step2(time, flux_mod, err_mod, dMu_dict, scale_dict, color_sort_ones, ROW, mu)
  File "ClusterEmcee2_linear_mu_2step.py", line 383, in perform_emcee_step2
    sausageplot_step2(max_theta[0], time, flux, max_theta[1], 5, err**2, dMu_dict, scale_dict, color_sort_ones, ROW, fig)
  File "ClusterEmcee2_linear_mu_2step.py", line 299, in sausageplot_step2
    parabola = np.polyfit(X, Y, 2)
  File "/home/thrush2/.local/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 585, in polyfit
    c, resids, rank, s = lstsq(lhs, rhs, rcond)
  File "/home/thrush2/.local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 2041, in lstsq
    0, work, lwork, iwork, 0)
ValueError: On entry to DLASCL parameter number 4 had an illegal value
