/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py:545: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "
('500', '600', 'normal')
Running object 500
0.0
{'i': 31, 'r': 25, 'z': 42, 'g': 32}
{'i': 0.49411544, 'r': 0.3214633, 'z': 0.72811073, 'g': 0.29783806}
Variable??
1.1469900489076212
Non-Variable source in g
Variable??
0.6118379026651383
Non-Variable source in r
Variable??
0.7828139836639465
Non-Variable source in i
Variable??
1.3734129502947885
Non-Variable source in z
Slope:       [0.7196219812357691, 1, 1, 1.1118381724457627]
Slope Error: [0.1996838253921096, 0, 0.23256120146417475, 0.3977078031885831]
intercepts:  [-0.030583504805359287, 0, -0.023505571492254518, -0.0187849162187268]
Int Error:   [0.029598915483400323, 0, 0.028591881116214076, 0.03450306322271933]
StDev:       [0.07707957, 0.048358988, 0.06247328, 0.11236863]
('ROW:', 500, 'Tau:', '0.5712264717129285', 'V:', '-0.8767566883795559')
Running object 501
0.0
{'i': 49, 'r': 52, 'z': 39, 'g': 28}
{'i': 0.53346664, 'r': 0.46585384, 'z': 0.67687833, 'g': 0.25195652}
Variable??
0.2264318759597345
Non-Variable source in g
Variable??
0.9225784844615874
Non-Variable source in r
Variable??
0.8989463906202999
Non-Variable source in i
Variable??
1.4317351971418275
Non-Variable source in z
Slope:       [1, 1, 1, 1]
Slope Error: [0.22018997081911215, 0, 0.18512514469402366, 0.12166733660251537]
intercepts:  [-0.007350703991109819, 0, -0.031013274442603767, -0.026868257599382384]
Int Error:   [0.01980899989851115, 0, 0.020880837391107236, 0.01754027423475545]
StDev:       [0.02630923, 0.07372062, 0.072106406, 0.08503837]
('ROW:', 501, 'Tau:', '3.999994402988782', 'V:', '-2.946587205675495')
Running object 502
0.0
{'i': 62, 'r': 48, 'z': 51, 'g': 17}
{'i': 0.6591624, 'r': 0.47584957, 'z': 0.7207629, 'g': 0.25969177}
Variable??
1.4431702647931697
Non-Variable source in g
Variable??
0.9610315177641005
Non-Variable source in r
Variable??
1.1894263086555643
Non-Variable source in i
Variable??
2.40395021290709
Non-Variable source in z
Slope:       [1.1963564751423268, 1, 0.43148068815420526, 0.9182307162716481]
Slope Error: [0.3596650031671185, 0, 0.10659905871039532, 0.18558207504851176]
intercepts:  [0.07460325889678343, 0, 0.011479215841169732, 0.054426346313381835]
Int Error:   [0.03918752984116953, 0, 0.014233520543260448, 0.026452164476941067]
StDev:       [0.04485964, 0.06595977, 0.08942336, 0.13770592]
('ROW:', 502, 'Tau:', '0.43810223578299545', 'V:', '-0.6685941602169065')
Running object 503
0.0
{'i': 82, 'r': 76, 'z': 166, 'g': 55}
{'i': 2.4417775, 'r': 1.6804459, 'z': 2.950488, 'g': 0.6014727}
Variable??
2.1485924944297117
Non-Variable source in g
Variable??
2.6726932043851255
Non-Variable source in r
Variable??
3.3002357674918565
Non-Variable source in i
Variable??
3.7082234018691205
Non-Variable source in z
Slope:       [1, 1, 1, 1]
Slope Error: [0.3981487887415212, 0, 0.0921109091728635, 0.09177302229242913]
intercepts:  [-0.0020514912176954913, 0, 0.0006937274670746341, -0.004519281037485742]
Int Error:   [0.012319421171172901, 0, 0.0037829539678967527, 0.0037359913152487847]
StDev:       [0.05311165, 0.06947523, 0.08596854, 0.14561145]
('ROW:', 503, 'Tau:', '3.9926665651044653', 'V:', '-2.986163099174875')
Running object 504
0.0
{'i': 40, 'r': 2, 'z': 114}
{'i': 0.528686, 'r': 0.19116665, 'z': 0.99312645, 'g': 0.0}
Variable??
0
Non-Variable source in g
Variable??
2.185633958259916
Non-Variable source in r
Variable??
0.8611345878532481
Non-Variable source in i
Variable??
0.3460053976402951
Non-Variable source in z
Slope:       [1, 1, 1, 1]
Slope Error: [0.0, 0, 0.0, 0.4533989832969927]
intercepts:  [0, 0, 0, 0.04575341543905942]
Int Error:   [0.0, 0, 0.0, 0.05255076531733726]
StDev:       [0.0, 0.022156984, 0.06594887, 0.10717512]
('ROW:', 504, 'Tau:', '3.9991242659270014', 'V:', '-1.335067672283442')
Traceback (most recent call last):
  File "ClusterEmcee2_linear_mu_2step.py", line 509, in <module>
    perform_emcee_step2(time, flux_mod, err_mod, dMu_dict, scale_dict, color_sort_ones, ROW, mu)
  File "ClusterEmcee2_linear_mu_2step.py", line 339, in perform_emcee_step2
    sausageplot_step2(max_theta[0], time, flux, max_theta[1], 5, err**2, dMu_dict, scale_dict, color_sort_ones, ROW, fig)
  File "ClusterEmcee2_linear_mu_2step.py", line 178, in sausageplot_step2
    ax4.legend()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 564, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/legend.py", line 386, in __init__
    self._init_legend_box(handles, labels, markerfirst)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/legend.py", line 655, in _init_legend_box
    fontsize, handlebox))
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/legend_handler.py", line 119, in legend_artist
    fontsize, handlebox.get_transform())
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/legend_handler.py", line 476, in create_artists
    self.update_prop(coll, barlinecols[0], legend)
IndexError: tuple index out of range
