/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py:545: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "
('1300', '1400', 'normal')
Running object 1300
0.0
{'i': 48, 'r': 53, 'z': 47, 'g': 14}
{'i': 0.63568234, 'r': 0.58850545, 'z': 0.79396325, 'g': 0.2539432}
Variable??
1.9007871367618534
Non-Variable source in g
Variable??
1.1819702982638591
Non-Variable source in r
Variable??
1.4086490477966902
Non-Variable source in i
Variable??
3.502214650528318
Non-Variable source in z
Slope:       [1.4507220259924107, 1, 0.470737529704349, 0.896332225765653]
Slope Error: [0.2945001599941945, 0, 0.17009729979285154, 0.20863056894212562]
intercepts:  [0.20704546825598613, 0, 0.00945083086762788, 0.0765540251889405]
Int Error:   [0.04947232948753643, 0, 0.024504817425820242, 0.03399482533236959]
StDev:       [0.054373898, 0.082188465, 0.09135292, 0.18825325]
('ROW:', 1300, 'Tau:', '0.0035521068300614633', 'V:', '-0.7740480791645769')
Running object 1301
0.0
{'i': 61, 'r': 52, 'z': 65, 'g': 23}
{'i': 0.69772166, 'r': 0.57036877, 'z': 0.8239112, 'g': 0.28864875}
Variable??
1.446365723718993
Non-Variable source in g
Variable??
1.3203387594704576
Non-Variable source in r
Variable??
1.336604765667488
Non-Variable source in i
Variable??
2.515043267267009
Non-Variable source in z
Slope:       [0.7047361460449406, 1, 1, 0.9883143435540198]
Slope Error: [0.3477433960234725, 0, 0.10864450474989856, 0.1692717961579259]
intercepts:  [0.002058455277680913, 0, -0.019551942762543906, 0.006119733567286123]
Int Error:   [0.0330396516103113, 0, 0.013787481563031693, 0.018961143784426673]
StDev:       [0.0473891, 0.07056109, 0.081920154, 0.1407813]
('ROW:', 1301, 'Tau:', '0.4190771583777096', 'V:', '-1.0593906985756534')
Running object 1302
0.0
{'i': 79, 'r': 61, 'z': 150}
{'i': 0.9570166, 'r': 0.54349726, 'z': 1.3367919, 'g': 0.0}
Variable??
0
Non-Variable source in g
Variable??
1.1608766436621272
Non-Variable source in r
Variable??
1.44695722359342
Non-Variable source in i
Variable??
1.7460482056552193
Non-Variable source in z
Slope:       [1, 1, 1, 1]
Slope Error: [0.0, 0, 0.08715140909471435, 0.08652043991904565]
intercepts:  [0, 0, -0.013468132493678064, 0.00568331195501004]
Int Error:   [0.0, 0, 0.009232724847636445, 0.008821440554381194]
StDev:       [0.0, 0.052770294, 0.06544219, 0.12046964]
('ROW:', 1302, 'Tau:', '0.45745673538398046', 'V:', '-1.6130015577955186')
Traceback (most recent call last):
  File "ClusterEmcee2_linear_mu_2step.py", line 509, in <module>
    perform_emcee_step2(time, flux_mod, err_mod, dMu_dict, scale_dict, color_sort_ones, ROW, mu)
  File "ClusterEmcee2_linear_mu_2step.py", line 339, in perform_emcee_step2
    sausageplot_step2(max_theta[0], time, flux, max_theta[1], 5, err**2, dMu_dict, scale_dict, color_sort_ones, ROW, fig)
  File "ClusterEmcee2_linear_mu_2step.py", line 178, in sausageplot_step2
    ax4.legend()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 564, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/legend.py", line 386, in __init__
    self._init_legend_box(handles, labels, markerfirst)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/legend.py", line 655, in _init_legend_box
    fontsize, handlebox))
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/legend_handler.py", line 119, in legend_artist
    fontsize, handlebox.get_transform())
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/legend_handler.py", line 476, in create_artists
    self.update_prop(coll, barlinecols[0], legend)
IndexError: tuple index out of range
